class Product:
    guide_product_list = {
        # product_id:product_detail
        4: {"image_src":"test_product_4.jpg",
            "product_name":"1",
            "sales_price":"999,999"},
        14:{"image_src":"test_product_14.jpg",
            "product_name":"2",
            "sales_price":"999,899"},
        44:{"image_src":"test_product_4.jpg",
            "product_name":"3",
            "sales_price":"999,799"},
        112: {"image_src":"test_product_4.jpg",
            "product_name":"4",
            "sales_price":"999,999"},
        114:{"image_src":"test_product_14.jpg",
            "product_name":"5",
            "sales_price":"999,899"},
        144:{"image_src":"test_product_44.jpg",
            "product_name":"6",
            "sales_price":"999,799"},
        224: {"image_src":"test_product_4.jpg",
            "product_name":"7",
            "sales_price":"999,999"},
        225:{"image_src":"test_product_14.jpg",
            "product_name":"8",
            "sales_price":"999,899"},
        244:{"image_src":"test_product_44.jpg",
            "product_name":"9",
            "sales_price":"999,799"},
        310: {"image_src":"test_product_4.jpg",
            "product_name":"10",
            "sales_price":"999,999"},
        314:{"image_src":"test_product_14.jpg",
            "product_name":"11",
            "sales_price":"999,899"},
        344:{"image_src":"test_product_44.jpg",
            "product_name":"12",
            "sales_price":"999,799"},
    }

    guide_product_list_t = {
        # product_id:product_detail
        114:{"image_src":"test_product_14.jpg",
            "product_name":"5",
            "sales_price":"999,899"},
        144:{"image_src":"test_product_44.jpg",
            "product_name":"6",
            "sales_price":"999,799"},
        224: {"image_src":"test_product_4.jpg",
            "product_name":"7",
            "sales_price":"999,999"},
        225:{"image_src":"test_product_14.jpg",
            "product_name":"8",
            "sales_price":"999,899"},
        244:{"image_src":"test_product_44.jpg",
            "product_name":"9",
            "sales_price":"999,799"},
        310: {"image_src":"test_product_4.jpg",
            "product_name":"10",
            "sales_price":"999,999"},
    }
