class Product:
    guide_product_list = {
        # product_id:product_detail
        4: {"thumbnail":"test_product_4.jpg",
            "brand":"더리얼 독",
            "product_name":"1",
            "sales_price":"999999"},
        14:{"thumbnail":"test_product_14.jpg",
            "brand":"더리얼 독",
            "product_name":"2",
            "sales_price":"999899"},
        44:{"thumbnail":"test_product_4.jpg",
            "brand":"더리얼 독",
            "product_name":"3",
            "sales_price":"999799"},
        112: {"thumbnail":"test_product_4.jpg",
            "brand":"밥이보약",
            "product_name":"4",
            "sales_price":"999999"},
        114:{"thumbnail":"test_product_14.jpg",
            "brand":"더리얼 독",
            "product_name":"5",
            "sales_price":"999899"},
        144:{"thumbnail":"test_product_44.jpg",
            "brand":"밥이보약",
            "product_name":"666666666666666666645444444444447777777777788679999900",
            "sales_price":"999799"},
        224: {"thumbnail":"test_product_4.jpg",
            "brand":"더리얼 독",
            "product_name":"7",
            "sales_price":"999999"},
        225:{"thumbnail":"test_product_14.jpg",
            "brand":"더리얼 독",
            "product_name":"8",
            "sales_price":"999899"},
        244:{"thumbnail":"test_product_44.jpg",
            "brand":"더리얼 독",
            "product_name":"9",
            "sales_price":"999799"},
        310: {"thumbnail":"test_product_4.jpg",
            "brand":"밥이보약",
            "product_name":"10",
            "sales_price":"999999"},
        314:{"thumbnail":"test_product_14.jpg",
            "brand":"더리얼 독",
            "product_name":"11",
            "sales_price":"999899"},
        344:{"thumbnail":"test_product_44.jpg",
            "brand":"더리얼 독",
            "product_name":"12",
            "sales_price":"999799"},
    }

    guide_product_list_t = {
        # product_id:product_detail
        114:{"thumbnail":"test_product_14.jpg",
            "brand":"밥이보약",
            "product_name":"5",
            "sales_price":"999899"},
        144:{"thumbnail":"test_product_44.jpg",
            "brand":"더리얼 독",
            "product_name":"6",
            "sales_price":"999799"},
        224: {"thumbnail":"test_product_4.jpg",
            "brand":"더리얼 독",
            "product_name":"7",
            "sales_price":"999999"},
        225:{"thumbnail":"test_product_14.jpg",
            "brand":"밥이보약",
            "product_name":"8",
            "sales_price":"999899"},
        244:{"thumbnail":"test_product_44.jpg",
            "brand":"더리얼 독",
            "product_name":"9",
            "sales_price":"999799"},
        310: {"thumbnail":"test_product_4.jpg",
            "brand":"더리얼 독",
            "product_name":"10",
            "sales_price":"999999"},
    }

    product_detail_src = {
        114:[
            "/thereal/thereal_raw/dog/thereal_raw_top_dog_00.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_pork_adult_01_360.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_pork_adult_02.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_03.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_04.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_05.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_pork_adult_06.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_review_07.jpg",
            "/thereal/thereal_lineup_dog_PC.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_lineup_dog_08-1.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_09.jpg"
        ],
        144:[
            "/thereal/thereal_raw/dog/thereal_raw_top_dog_00.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_pork_adult_01_360.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_pork_adult_02.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_03.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_04.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_05.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_pork_adult_06.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_review_07.jpg",
            "/thereal/thereal_lineup_dog_PC.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_lineup_dog_08-1.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_09.jpg"
        ],
        224:[
            "/thereal/thereal_raw/dog/thereal_raw_top_dog_00.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_pork_adult_01_360.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_pork_adult_02.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_03.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_04.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_05.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_pork_adult_06.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_review_07.jpg",
            "/thereal/thereal_lineup_dog_PC.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_lineup_dog_08-1.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_09.jpg"
        ],
        225:[
            "/thereal/thereal_raw/dog/thereal_raw_top_dog_00.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_pork_adult_01_360.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_pork_adult_02.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_03.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_04.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_05.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_pork_adult_06.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_review_07.jpg",
            "/thereal/thereal_lineup_dog_PC.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_lineup_dog_08-1.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_09.jpg"
        ],
        244:[
            "/thereal/thereal_raw/dog/thereal_raw_top_dog_00.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_pork_adult_01_360.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_pork_adult_02.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_03.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_04.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_05.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_pork_adult_06.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_review_07.jpg",
            "/thereal/thereal_lineup_dog_PC.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_lineup_dog_08-1.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_09.jpg"
        ],
        310:[
            "/thereal/thereal_raw/dog/thereal_raw_top_dog_00.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_pork_adult_01_360.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_pork_adult_02.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_03.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_04.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_05.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_pork_adult_06.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_review_07.jpg",
            "/thereal/thereal_lineup_dog_PC.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_lineup_dog_08-1.jpg",
            "/thereal/thereal_raw/dog/thereal_raw_09.jpg"
        ],
    }
